// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metapb.proto

#ifndef PROTOBUF_INCLUDED_metapb_2eproto
#define PROTOBUF_INCLUDED_metapb_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "gogoproto/gogo.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_metapb_2eproto 

namespace protobuf_metapb_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[9];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_metapb_2eproto
namespace metapb {
class Cluster;
class ClusterDefaultTypeInternal;
extern ClusterDefaultTypeInternal _Cluster_default_instance_;
class Peer;
class PeerDefaultTypeInternal;
extern PeerDefaultTypeInternal _Peer_default_instance_;
class PeerStats;
class PeerStatsDefaultTypeInternal;
extern PeerStatsDefaultTypeInternal _PeerStats_default_instance_;
class Progress;
class ProgressDefaultTypeInternal;
extern ProgressDefaultTypeInternal _Progress_default_instance_;
class Region;
class RegionDefaultTypeInternal;
extern RegionDefaultTypeInternal _Region_default_instance_;
class RegionEpoch;
class RegionEpochDefaultTypeInternal;
extern RegionEpochDefaultTypeInternal _RegionEpoch_default_instance_;
class RegionLocalState;
class RegionLocalStateDefaultTypeInternal;
extern RegionLocalStateDefaultTypeInternal _RegionLocalState_default_instance_;
class Store;
class StoreDefaultTypeInternal;
extern StoreDefaultTypeInternal _Store_default_instance_;
class StoreLabel;
class StoreLabelDefaultTypeInternal;
extern StoreLabelDefaultTypeInternal _StoreLabel_default_instance_;
}  // namespace metapb
namespace google {
namespace protobuf {
template<> ::metapb::Cluster* Arena::CreateMaybeMessage<::metapb::Cluster>(Arena*);
template<> ::metapb::Peer* Arena::CreateMaybeMessage<::metapb::Peer>(Arena*);
template<> ::metapb::PeerStats* Arena::CreateMaybeMessage<::metapb::PeerStats>(Arena*);
template<> ::metapb::Progress* Arena::CreateMaybeMessage<::metapb::Progress>(Arena*);
template<> ::metapb::Region* Arena::CreateMaybeMessage<::metapb::Region>(Arena*);
template<> ::metapb::RegionEpoch* Arena::CreateMaybeMessage<::metapb::RegionEpoch>(Arena*);
template<> ::metapb::RegionLocalState* Arena::CreateMaybeMessage<::metapb::RegionLocalState>(Arena*);
template<> ::metapb::Store* Arena::CreateMaybeMessage<::metapb::Store>(Arena*);
template<> ::metapb::StoreLabel* Arena::CreateMaybeMessage<::metapb::StoreLabel>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace metapb {

enum StoreState {
  Up = 0,
  Offline = 1,
  Tombstone = 2,
  StoreState_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  StoreState_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool StoreState_IsValid(int value);
const StoreState StoreState_MIN = Up;
const StoreState StoreState_MAX = Tombstone;
const int StoreState_ARRAYSIZE = StoreState_MAX + 1;

const ::google::protobuf::EnumDescriptor* StoreState_descriptor();
inline const ::std::string& StoreState_Name(StoreState value) {
  return ::google::protobuf::internal::NameOfEnum(
    StoreState_descriptor(), value);
}
inline bool StoreState_Parse(
    const ::std::string& name, StoreState* value) {
  return ::google::protobuf::internal::ParseNamedEnum<StoreState>(
    StoreState_descriptor(), name, value);
}
enum ProgressState {
  Probe = 0,
  Replicate = 1,
  Snapshot = 2,
  ProgressState_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  ProgressState_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool ProgressState_IsValid(int value);
const ProgressState ProgressState_MIN = Probe;
const ProgressState ProgressState_MAX = Snapshot;
const int ProgressState_ARRAYSIZE = ProgressState_MAX + 1;

const ::google::protobuf::EnumDescriptor* ProgressState_descriptor();
inline const ::std::string& ProgressState_Name(ProgressState value) {
  return ::google::protobuf::internal::NameOfEnum(
    ProgressState_descriptor(), value);
}
inline bool ProgressState_Parse(
    const ::std::string& name, ProgressState* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ProgressState>(
    ProgressState_descriptor(), name, value);
}
// ===================================================================

class Cluster : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:metapb.Cluster) */ {
 public:
  Cluster();
  virtual ~Cluster();

  Cluster(const Cluster& from);

  inline Cluster& operator=(const Cluster& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Cluster(Cluster&& from) noexcept
    : Cluster() {
    *this = ::std::move(from);
  }

  inline Cluster& operator=(Cluster&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Cluster& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Cluster* internal_default_instance() {
    return reinterpret_cast<const Cluster*>(
               &_Cluster_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Cluster* other);
  friend void swap(Cluster& a, Cluster& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Cluster* New() const final {
    return CreateMaybeMessage<Cluster>(NULL);
  }

  Cluster* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Cluster>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Cluster& from);
  void MergeFrom(const Cluster& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Cluster* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint64 id() const;
  void set_id(::google::protobuf::uint64 value);

  // uint32 max_peer_count = 2;
  void clear_max_peer_count();
  static const int kMaxPeerCountFieldNumber = 2;
  ::google::protobuf::uint32 max_peer_count() const;
  void set_max_peer_count(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:metapb.Cluster)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 id_;
  ::google::protobuf::uint32 max_peer_count_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_metapb_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class StoreLabel : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:metapb.StoreLabel) */ {
 public:
  StoreLabel();
  virtual ~StoreLabel();

  StoreLabel(const StoreLabel& from);

  inline StoreLabel& operator=(const StoreLabel& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  StoreLabel(StoreLabel&& from) noexcept
    : StoreLabel() {
    *this = ::std::move(from);
  }

  inline StoreLabel& operator=(StoreLabel&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const StoreLabel& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StoreLabel* internal_default_instance() {
    return reinterpret_cast<const StoreLabel*>(
               &_StoreLabel_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(StoreLabel* other);
  friend void swap(StoreLabel& a, StoreLabel& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline StoreLabel* New() const final {
    return CreateMaybeMessage<StoreLabel>(NULL);
  }

  StoreLabel* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<StoreLabel>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const StoreLabel& from);
  void MergeFrom(const StoreLabel& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StoreLabel* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string key = 1;
  void clear_key();
  static const int kKeyFieldNumber = 1;
  const ::std::string& key() const;
  void set_key(const ::std::string& value);
  #if LANG_CXX11
  void set_key(::std::string&& value);
  #endif
  void set_key(const char* value);
  void set_key(const char* value, size_t size);
  ::std::string* mutable_key();
  ::std::string* release_key();
  void set_allocated_key(::std::string* key);

  // string value = 2;
  void clear_value();
  static const int kValueFieldNumber = 2;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  #if LANG_CXX11
  void set_value(::std::string&& value);
  #endif
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // @@protoc_insertion_point(class_scope:metapb.StoreLabel)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr key_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_metapb_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Store : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:metapb.Store) */ {
 public:
  Store();
  virtual ~Store();

  Store(const Store& from);

  inline Store& operator=(const Store& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Store(Store&& from) noexcept
    : Store() {
    *this = ::std::move(from);
  }

  inline Store& operator=(Store&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Store& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Store* internal_default_instance() {
    return reinterpret_cast<const Store*>(
               &_Store_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(Store* other);
  friend void swap(Store& a, Store& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Store* New() const final {
    return CreateMaybeMessage<Store>(NULL);
  }

  Store* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Store>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Store& from);
  void MergeFrom(const Store& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Store* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .metapb.StoreLabel labels = 4;
  int labels_size() const;
  void clear_labels();
  static const int kLabelsFieldNumber = 4;
  ::metapb::StoreLabel* mutable_labels(int index);
  ::google::protobuf::RepeatedPtrField< ::metapb::StoreLabel >*
      mutable_labels();
  const ::metapb::StoreLabel& labels(int index) const;
  ::metapb::StoreLabel* add_labels();
  const ::google::protobuf::RepeatedPtrField< ::metapb::StoreLabel >&
      labels() const;

  // string address = 2;
  void clear_address();
  static const int kAddressFieldNumber = 2;
  const ::std::string& address() const;
  void set_address(const ::std::string& value);
  #if LANG_CXX11
  void set_address(::std::string&& value);
  #endif
  void set_address(const char* value);
  void set_address(const char* value, size_t size);
  ::std::string* mutable_address();
  ::std::string* release_address();
  void set_allocated_address(::std::string* address);

  // string version = 5;
  void clear_version();
  static const int kVersionFieldNumber = 5;
  const ::std::string& version() const;
  void set_version(const ::std::string& value);
  #if LANG_CXX11
  void set_version(::std::string&& value);
  #endif
  void set_version(const char* value);
  void set_version(const char* value, size_t size);
  ::std::string* mutable_version();
  ::std::string* release_version();
  void set_allocated_version(::std::string* version);

  // uint64 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint64 id() const;
  void set_id(::google::protobuf::uint64 value);

  // .metapb.StoreState state = 3;
  void clear_state();
  static const int kStateFieldNumber = 3;
  ::metapb::StoreState state() const;
  void set_state(::metapb::StoreState value);

  // @@protoc_insertion_point(class_scope:metapb.Store)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::metapb::StoreLabel > labels_;
  ::google::protobuf::internal::ArenaStringPtr address_;
  ::google::protobuf::internal::ArenaStringPtr version_;
  ::google::protobuf::uint64 id_;
  int state_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_metapb_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RegionEpoch : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:metapb.RegionEpoch) */ {
 public:
  RegionEpoch();
  virtual ~RegionEpoch();

  RegionEpoch(const RegionEpoch& from);

  inline RegionEpoch& operator=(const RegionEpoch& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RegionEpoch(RegionEpoch&& from) noexcept
    : RegionEpoch() {
    *this = ::std::move(from);
  }

  inline RegionEpoch& operator=(RegionEpoch&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const RegionEpoch& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RegionEpoch* internal_default_instance() {
    return reinterpret_cast<const RegionEpoch*>(
               &_RegionEpoch_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(RegionEpoch* other);
  friend void swap(RegionEpoch& a, RegionEpoch& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RegionEpoch* New() const final {
    return CreateMaybeMessage<RegionEpoch>(NULL);
  }

  RegionEpoch* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RegionEpoch>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RegionEpoch& from);
  void MergeFrom(const RegionEpoch& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RegionEpoch* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 conf_ver = 1;
  void clear_conf_ver();
  static const int kConfVerFieldNumber = 1;
  ::google::protobuf::uint64 conf_ver() const;
  void set_conf_ver(::google::protobuf::uint64 value);

  // uint64 version = 2;
  void clear_version();
  static const int kVersionFieldNumber = 2;
  ::google::protobuf::uint64 version() const;
  void set_version(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:metapb.RegionEpoch)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 conf_ver_;
  ::google::protobuf::uint64 version_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_metapb_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Region : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:metapb.Region) */ {
 public:
  Region();
  virtual ~Region();

  Region(const Region& from);

  inline Region& operator=(const Region& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Region(Region&& from) noexcept
    : Region() {
    *this = ::std::move(from);
  }

  inline Region& operator=(Region&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Region& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Region* internal_default_instance() {
    return reinterpret_cast<const Region*>(
               &_Region_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(Region* other);
  friend void swap(Region& a, Region& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Region* New() const final {
    return CreateMaybeMessage<Region>(NULL);
  }

  Region* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Region>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Region& from);
  void MergeFrom(const Region& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Region* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .metapb.Peer peers = 5;
  int peers_size() const;
  void clear_peers();
  static const int kPeersFieldNumber = 5;
  ::metapb::Peer* mutable_peers(int index);
  ::google::protobuf::RepeatedPtrField< ::metapb::Peer >*
      mutable_peers();
  const ::metapb::Peer& peers(int index) const;
  ::metapb::Peer* add_peers();
  const ::google::protobuf::RepeatedPtrField< ::metapb::Peer >&
      peers() const;

  // bytes start_key = 2;
  void clear_start_key();
  static const int kStartKeyFieldNumber = 2;
  const ::std::string& start_key() const;
  void set_start_key(const ::std::string& value);
  #if LANG_CXX11
  void set_start_key(::std::string&& value);
  #endif
  void set_start_key(const char* value);
  void set_start_key(const void* value, size_t size);
  ::std::string* mutable_start_key();
  ::std::string* release_start_key();
  void set_allocated_start_key(::std::string* start_key);

  // bytes end_key = 3;
  void clear_end_key();
  static const int kEndKeyFieldNumber = 3;
  const ::std::string& end_key() const;
  void set_end_key(const ::std::string& value);
  #if LANG_CXX11
  void set_end_key(::std::string&& value);
  #endif
  void set_end_key(const char* value);
  void set_end_key(const void* value, size_t size);
  ::std::string* mutable_end_key();
  ::std::string* release_end_key();
  void set_allocated_end_key(::std::string* end_key);

  // .metapb.RegionEpoch region_epoch = 4;
  bool has_region_epoch() const;
  void clear_region_epoch();
  static const int kRegionEpochFieldNumber = 4;
  private:
  const ::metapb::RegionEpoch& _internal_region_epoch() const;
  public:
  const ::metapb::RegionEpoch& region_epoch() const;
  ::metapb::RegionEpoch* release_region_epoch();
  ::metapb::RegionEpoch* mutable_region_epoch();
  void set_allocated_region_epoch(::metapb::RegionEpoch* region_epoch);

  // uint64 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint64 id() const;
  void set_id(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:metapb.Region)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::metapb::Peer > peers_;
  ::google::protobuf::internal::ArenaStringPtr start_key_;
  ::google::protobuf::internal::ArenaStringPtr end_key_;
  ::metapb::RegionEpoch* region_epoch_;
  ::google::protobuf::uint64 id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_metapb_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Peer : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:metapb.Peer) */ {
 public:
  Peer();
  virtual ~Peer();

  Peer(const Peer& from);

  inline Peer& operator=(const Peer& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Peer(Peer&& from) noexcept
    : Peer() {
    *this = ::std::move(from);
  }

  inline Peer& operator=(Peer&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Peer& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Peer* internal_default_instance() {
    return reinterpret_cast<const Peer*>(
               &_Peer_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(Peer* other);
  friend void swap(Peer& a, Peer& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Peer* New() const final {
    return CreateMaybeMessage<Peer>(NULL);
  }

  Peer* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Peer>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Peer& from);
  void MergeFrom(const Peer& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Peer* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint64 id() const;
  void set_id(::google::protobuf::uint64 value);

  // uint64 store_id = 2;
  void clear_store_id();
  static const int kStoreIdFieldNumber = 2;
  ::google::protobuf::uint64 store_id() const;
  void set_store_id(::google::protobuf::uint64 value);

  // bool is_learner = 3;
  void clear_is_learner();
  static const int kIsLearnerFieldNumber = 3;
  bool is_learner() const;
  void set_is_learner(bool value);

  // @@protoc_insertion_point(class_scope:metapb.Peer)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 id_;
  ::google::protobuf::uint64 store_id_;
  bool is_learner_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_metapb_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RegionLocalState : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:metapb.RegionLocalState) */ {
 public:
  RegionLocalState();
  virtual ~RegionLocalState();

  RegionLocalState(const RegionLocalState& from);

  inline RegionLocalState& operator=(const RegionLocalState& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RegionLocalState(RegionLocalState&& from) noexcept
    : RegionLocalState() {
    *this = ::std::move(from);
  }

  inline RegionLocalState& operator=(RegionLocalState&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const RegionLocalState& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RegionLocalState* internal_default_instance() {
    return reinterpret_cast<const RegionLocalState*>(
               &_RegionLocalState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(RegionLocalState* other);
  friend void swap(RegionLocalState& a, RegionLocalState& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RegionLocalState* New() const final {
    return CreateMaybeMessage<RegionLocalState>(NULL);
  }

  RegionLocalState* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RegionLocalState>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RegionLocalState& from);
  void MergeFrom(const RegionLocalState& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RegionLocalState* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 last_index = 1;
  void clear_last_index();
  static const int kLastIndexFieldNumber = 1;
  ::google::protobuf::uint64 last_index() const;
  void set_last_index(::google::protobuf::uint64 value);

  // uint64 committed_index = 2;
  void clear_committed_index();
  static const int kCommittedIndexFieldNumber = 2;
  ::google::protobuf::uint64 committed_index() const;
  void set_committed_index(::google::protobuf::uint64 value);

  // uint64 applied_index = 3;
  void clear_applied_index();
  static const int kAppliedIndexFieldNumber = 3;
  ::google::protobuf::uint64 applied_index() const;
  void set_applied_index(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:metapb.RegionLocalState)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 last_index_;
  ::google::protobuf::uint64 committed_index_;
  ::google::protobuf::uint64 applied_index_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_metapb_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Progress : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:metapb.Progress) */ {
 public:
  Progress();
  virtual ~Progress();

  Progress(const Progress& from);

  inline Progress& operator=(const Progress& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Progress(Progress&& from) noexcept
    : Progress() {
    *this = ::std::move(from);
  }

  inline Progress& operator=(Progress&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Progress& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Progress* internal_default_instance() {
    return reinterpret_cast<const Progress*>(
               &_Progress_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  void Swap(Progress* other);
  friend void swap(Progress& a, Progress& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Progress* New() const final {
    return CreateMaybeMessage<Progress>(NULL);
  }

  Progress* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Progress>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Progress& from);
  void MergeFrom(const Progress& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Progress* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 matched = 1;
  void clear_matched();
  static const int kMatchedFieldNumber = 1;
  ::google::protobuf::uint64 matched() const;
  void set_matched(::google::protobuf::uint64 value);

  // uint64 next_idx = 2;
  void clear_next_idx();
  static const int kNextIdxFieldNumber = 2;
  ::google::protobuf::uint64 next_idx() const;
  void set_next_idx(::google::protobuf::uint64 value);

  // uint64 pending_snapshot = 4;
  void clear_pending_snapshot();
  static const int kPendingSnapshotFieldNumber = 4;
  ::google::protobuf::uint64 pending_snapshot() const;
  void set_pending_snapshot(::google::protobuf::uint64 value);

  // bool paused = 3;
  void clear_paused();
  static const int kPausedFieldNumber = 3;
  bool paused() const;
  void set_paused(bool value);

  // bool is_learner = 5;
  void clear_is_learner();
  static const int kIsLearnerFieldNumber = 5;
  bool is_learner() const;
  void set_is_learner(bool value);

  // .metapb.ProgressState state = 6;
  void clear_state();
  static const int kStateFieldNumber = 6;
  ::metapb::ProgressState state() const;
  void set_state(::metapb::ProgressState value);

  // @@protoc_insertion_point(class_scope:metapb.Progress)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 matched_;
  ::google::protobuf::uint64 next_idx_;
  ::google::protobuf::uint64 pending_snapshot_;
  bool paused_;
  bool is_learner_;
  int state_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_metapb_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PeerStats : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:metapb.PeerStats) */ {
 public:
  PeerStats();
  virtual ~PeerStats();

  PeerStats(const PeerStats& from);

  inline PeerStats& operator=(const PeerStats& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PeerStats(PeerStats&& from) noexcept
    : PeerStats() {
    *this = ::std::move(from);
  }

  inline PeerStats& operator=(PeerStats&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PeerStats& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PeerStats* internal_default_instance() {
    return reinterpret_cast<const PeerStats*>(
               &_PeerStats_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  void Swap(PeerStats* other);
  friend void swap(PeerStats& a, PeerStats& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PeerStats* New() const final {
    return CreateMaybeMessage<PeerStats>(NULL);
  }

  PeerStats* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PeerStats>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const PeerStats& from);
  void MergeFrom(const PeerStats& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PeerStats* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .metapb.Peer peer = 1;
  bool has_peer() const;
  void clear_peer();
  static const int kPeerFieldNumber = 1;
  private:
  const ::metapb::Peer& _internal_peer() const;
  public:
  const ::metapb::Peer& peer() const;
  ::metapb::Peer* release_peer();
  ::metapb::Peer* mutable_peer();
  void set_allocated_peer(::metapb::Peer* peer);

  // uint64 down_seconds = 2;
  void clear_down_seconds();
  static const int kDownSecondsFieldNumber = 2;
  ::google::protobuf::uint64 down_seconds() const;
  void set_down_seconds(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:metapb.PeerStats)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::metapb::Peer* peer_;
  ::google::protobuf::uint64 down_seconds_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_metapb_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Cluster

// uint64 id = 1;
inline void Cluster::clear_id() {
  id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Cluster::id() const {
  // @@protoc_insertion_point(field_get:metapb.Cluster.id)
  return id_;
}
inline void Cluster::set_id(::google::protobuf::uint64 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:metapb.Cluster.id)
}

// uint32 max_peer_count = 2;
inline void Cluster::clear_max_peer_count() {
  max_peer_count_ = 0u;
}
inline ::google::protobuf::uint32 Cluster::max_peer_count() const {
  // @@protoc_insertion_point(field_get:metapb.Cluster.max_peer_count)
  return max_peer_count_;
}
inline void Cluster::set_max_peer_count(::google::protobuf::uint32 value) {
  
  max_peer_count_ = value;
  // @@protoc_insertion_point(field_set:metapb.Cluster.max_peer_count)
}

// -------------------------------------------------------------------

// StoreLabel

// string key = 1;
inline void StoreLabel::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& StoreLabel::key() const {
  // @@protoc_insertion_point(field_get:metapb.StoreLabel.key)
  return key_.GetNoArena();
}
inline void StoreLabel::set_key(const ::std::string& value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:metapb.StoreLabel.key)
}
#if LANG_CXX11
inline void StoreLabel::set_key(::std::string&& value) {
  
  key_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:metapb.StoreLabel.key)
}
#endif
inline void StoreLabel::set_key(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:metapb.StoreLabel.key)
}
inline void StoreLabel::set_key(const char* value, size_t size) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:metapb.StoreLabel.key)
}
inline ::std::string* StoreLabel::mutable_key() {
  
  // @@protoc_insertion_point(field_mutable:metapb.StoreLabel.key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* StoreLabel::release_key() {
  // @@protoc_insertion_point(field_release:metapb.StoreLabel.key)
  
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void StoreLabel::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    
  } else {
    
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:metapb.StoreLabel.key)
}

// string value = 2;
inline void StoreLabel::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& StoreLabel::value() const {
  // @@protoc_insertion_point(field_get:metapb.StoreLabel.value)
  return value_.GetNoArena();
}
inline void StoreLabel::set_value(const ::std::string& value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:metapb.StoreLabel.value)
}
#if LANG_CXX11
inline void StoreLabel::set_value(::std::string&& value) {
  
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:metapb.StoreLabel.value)
}
#endif
inline void StoreLabel::set_value(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:metapb.StoreLabel.value)
}
inline void StoreLabel::set_value(const char* value, size_t size) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:metapb.StoreLabel.value)
}
inline ::std::string* StoreLabel::mutable_value() {
  
  // @@protoc_insertion_point(field_mutable:metapb.StoreLabel.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* StoreLabel::release_value() {
  // @@protoc_insertion_point(field_release:metapb.StoreLabel.value)
  
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void StoreLabel::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:metapb.StoreLabel.value)
}

// -------------------------------------------------------------------

// Store

// uint64 id = 1;
inline void Store::clear_id() {
  id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Store::id() const {
  // @@protoc_insertion_point(field_get:metapb.Store.id)
  return id_;
}
inline void Store::set_id(::google::protobuf::uint64 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:metapb.Store.id)
}

// string address = 2;
inline void Store::clear_address() {
  address_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Store::address() const {
  // @@protoc_insertion_point(field_get:metapb.Store.address)
  return address_.GetNoArena();
}
inline void Store::set_address(const ::std::string& value) {
  
  address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:metapb.Store.address)
}
#if LANG_CXX11
inline void Store::set_address(::std::string&& value) {
  
  address_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:metapb.Store.address)
}
#endif
inline void Store::set_address(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:metapb.Store.address)
}
inline void Store::set_address(const char* value, size_t size) {
  
  address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:metapb.Store.address)
}
inline ::std::string* Store::mutable_address() {
  
  // @@protoc_insertion_point(field_mutable:metapb.Store.address)
  return address_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Store::release_address() {
  // @@protoc_insertion_point(field_release:metapb.Store.address)
  
  return address_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Store::set_allocated_address(::std::string* address) {
  if (address != NULL) {
    
  } else {
    
  }
  address_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), address);
  // @@protoc_insertion_point(field_set_allocated:metapb.Store.address)
}

// .metapb.StoreState state = 3;
inline void Store::clear_state() {
  state_ = 0;
}
inline ::metapb::StoreState Store::state() const {
  // @@protoc_insertion_point(field_get:metapb.Store.state)
  return static_cast< ::metapb::StoreState >(state_);
}
inline void Store::set_state(::metapb::StoreState value) {
  
  state_ = value;
  // @@protoc_insertion_point(field_set:metapb.Store.state)
}

// repeated .metapb.StoreLabel labels = 4;
inline int Store::labels_size() const {
  return labels_.size();
}
inline void Store::clear_labels() {
  labels_.Clear();
}
inline ::metapb::StoreLabel* Store::mutable_labels(int index) {
  // @@protoc_insertion_point(field_mutable:metapb.Store.labels)
  return labels_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::metapb::StoreLabel >*
Store::mutable_labels() {
  // @@protoc_insertion_point(field_mutable_list:metapb.Store.labels)
  return &labels_;
}
inline const ::metapb::StoreLabel& Store::labels(int index) const {
  // @@protoc_insertion_point(field_get:metapb.Store.labels)
  return labels_.Get(index);
}
inline ::metapb::StoreLabel* Store::add_labels() {
  // @@protoc_insertion_point(field_add:metapb.Store.labels)
  return labels_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::metapb::StoreLabel >&
Store::labels() const {
  // @@protoc_insertion_point(field_list:metapb.Store.labels)
  return labels_;
}

// string version = 5;
inline void Store::clear_version() {
  version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Store::version() const {
  // @@protoc_insertion_point(field_get:metapb.Store.version)
  return version_.GetNoArena();
}
inline void Store::set_version(const ::std::string& value) {
  
  version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:metapb.Store.version)
}
#if LANG_CXX11
inline void Store::set_version(::std::string&& value) {
  
  version_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:metapb.Store.version)
}
#endif
inline void Store::set_version(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:metapb.Store.version)
}
inline void Store::set_version(const char* value, size_t size) {
  
  version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:metapb.Store.version)
}
inline ::std::string* Store::mutable_version() {
  
  // @@protoc_insertion_point(field_mutable:metapb.Store.version)
  return version_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Store::release_version() {
  // @@protoc_insertion_point(field_release:metapb.Store.version)
  
  return version_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Store::set_allocated_version(::std::string* version) {
  if (version != NULL) {
    
  } else {
    
  }
  version_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), version);
  // @@protoc_insertion_point(field_set_allocated:metapb.Store.version)
}

// -------------------------------------------------------------------

// RegionEpoch

// uint64 conf_ver = 1;
inline void RegionEpoch::clear_conf_ver() {
  conf_ver_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 RegionEpoch::conf_ver() const {
  // @@protoc_insertion_point(field_get:metapb.RegionEpoch.conf_ver)
  return conf_ver_;
}
inline void RegionEpoch::set_conf_ver(::google::protobuf::uint64 value) {
  
  conf_ver_ = value;
  // @@protoc_insertion_point(field_set:metapb.RegionEpoch.conf_ver)
}

// uint64 version = 2;
inline void RegionEpoch::clear_version() {
  version_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 RegionEpoch::version() const {
  // @@protoc_insertion_point(field_get:metapb.RegionEpoch.version)
  return version_;
}
inline void RegionEpoch::set_version(::google::protobuf::uint64 value) {
  
  version_ = value;
  // @@protoc_insertion_point(field_set:metapb.RegionEpoch.version)
}

// -------------------------------------------------------------------

// Region

// uint64 id = 1;
inline void Region::clear_id() {
  id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Region::id() const {
  // @@protoc_insertion_point(field_get:metapb.Region.id)
  return id_;
}
inline void Region::set_id(::google::protobuf::uint64 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:metapb.Region.id)
}

// bytes start_key = 2;
inline void Region::clear_start_key() {
  start_key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Region::start_key() const {
  // @@protoc_insertion_point(field_get:metapb.Region.start_key)
  return start_key_.GetNoArena();
}
inline void Region::set_start_key(const ::std::string& value) {
  
  start_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:metapb.Region.start_key)
}
#if LANG_CXX11
inline void Region::set_start_key(::std::string&& value) {
  
  start_key_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:metapb.Region.start_key)
}
#endif
inline void Region::set_start_key(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  start_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:metapb.Region.start_key)
}
inline void Region::set_start_key(const void* value, size_t size) {
  
  start_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:metapb.Region.start_key)
}
inline ::std::string* Region::mutable_start_key() {
  
  // @@protoc_insertion_point(field_mutable:metapb.Region.start_key)
  return start_key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Region::release_start_key() {
  // @@protoc_insertion_point(field_release:metapb.Region.start_key)
  
  return start_key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Region::set_allocated_start_key(::std::string* start_key) {
  if (start_key != NULL) {
    
  } else {
    
  }
  start_key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), start_key);
  // @@protoc_insertion_point(field_set_allocated:metapb.Region.start_key)
}

// bytes end_key = 3;
inline void Region::clear_end_key() {
  end_key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Region::end_key() const {
  // @@protoc_insertion_point(field_get:metapb.Region.end_key)
  return end_key_.GetNoArena();
}
inline void Region::set_end_key(const ::std::string& value) {
  
  end_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:metapb.Region.end_key)
}
#if LANG_CXX11
inline void Region::set_end_key(::std::string&& value) {
  
  end_key_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:metapb.Region.end_key)
}
#endif
inline void Region::set_end_key(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  end_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:metapb.Region.end_key)
}
inline void Region::set_end_key(const void* value, size_t size) {
  
  end_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:metapb.Region.end_key)
}
inline ::std::string* Region::mutable_end_key() {
  
  // @@protoc_insertion_point(field_mutable:metapb.Region.end_key)
  return end_key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Region::release_end_key() {
  // @@protoc_insertion_point(field_release:metapb.Region.end_key)
  
  return end_key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Region::set_allocated_end_key(::std::string* end_key) {
  if (end_key != NULL) {
    
  } else {
    
  }
  end_key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), end_key);
  // @@protoc_insertion_point(field_set_allocated:metapb.Region.end_key)
}

// .metapb.RegionEpoch region_epoch = 4;
inline bool Region::has_region_epoch() const {
  return this != internal_default_instance() && region_epoch_ != NULL;
}
inline void Region::clear_region_epoch() {
  if (GetArenaNoVirtual() == NULL && region_epoch_ != NULL) {
    delete region_epoch_;
  }
  region_epoch_ = NULL;
}
inline const ::metapb::RegionEpoch& Region::_internal_region_epoch() const {
  return *region_epoch_;
}
inline const ::metapb::RegionEpoch& Region::region_epoch() const {
  const ::metapb::RegionEpoch* p = region_epoch_;
  // @@protoc_insertion_point(field_get:metapb.Region.region_epoch)
  return p != NULL ? *p : *reinterpret_cast<const ::metapb::RegionEpoch*>(
      &::metapb::_RegionEpoch_default_instance_);
}
inline ::metapb::RegionEpoch* Region::release_region_epoch() {
  // @@protoc_insertion_point(field_release:metapb.Region.region_epoch)
  
  ::metapb::RegionEpoch* temp = region_epoch_;
  region_epoch_ = NULL;
  return temp;
}
inline ::metapb::RegionEpoch* Region::mutable_region_epoch() {
  
  if (region_epoch_ == NULL) {
    auto* p = CreateMaybeMessage<::metapb::RegionEpoch>(GetArenaNoVirtual());
    region_epoch_ = p;
  }
  // @@protoc_insertion_point(field_mutable:metapb.Region.region_epoch)
  return region_epoch_;
}
inline void Region::set_allocated_region_epoch(::metapb::RegionEpoch* region_epoch) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete region_epoch_;
  }
  if (region_epoch) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      region_epoch = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, region_epoch, submessage_arena);
    }
    
  } else {
    
  }
  region_epoch_ = region_epoch;
  // @@protoc_insertion_point(field_set_allocated:metapb.Region.region_epoch)
}

// repeated .metapb.Peer peers = 5;
inline int Region::peers_size() const {
  return peers_.size();
}
inline void Region::clear_peers() {
  peers_.Clear();
}
inline ::metapb::Peer* Region::mutable_peers(int index) {
  // @@protoc_insertion_point(field_mutable:metapb.Region.peers)
  return peers_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::metapb::Peer >*
Region::mutable_peers() {
  // @@protoc_insertion_point(field_mutable_list:metapb.Region.peers)
  return &peers_;
}
inline const ::metapb::Peer& Region::peers(int index) const {
  // @@protoc_insertion_point(field_get:metapb.Region.peers)
  return peers_.Get(index);
}
inline ::metapb::Peer* Region::add_peers() {
  // @@protoc_insertion_point(field_add:metapb.Region.peers)
  return peers_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::metapb::Peer >&
Region::peers() const {
  // @@protoc_insertion_point(field_list:metapb.Region.peers)
  return peers_;
}

// -------------------------------------------------------------------

// Peer

// uint64 id = 1;
inline void Peer::clear_id() {
  id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Peer::id() const {
  // @@protoc_insertion_point(field_get:metapb.Peer.id)
  return id_;
}
inline void Peer::set_id(::google::protobuf::uint64 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:metapb.Peer.id)
}

// uint64 store_id = 2;
inline void Peer::clear_store_id() {
  store_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Peer::store_id() const {
  // @@protoc_insertion_point(field_get:metapb.Peer.store_id)
  return store_id_;
}
inline void Peer::set_store_id(::google::protobuf::uint64 value) {
  
  store_id_ = value;
  // @@protoc_insertion_point(field_set:metapb.Peer.store_id)
}

// bool is_learner = 3;
inline void Peer::clear_is_learner() {
  is_learner_ = false;
}
inline bool Peer::is_learner() const {
  // @@protoc_insertion_point(field_get:metapb.Peer.is_learner)
  return is_learner_;
}
inline void Peer::set_is_learner(bool value) {
  
  is_learner_ = value;
  // @@protoc_insertion_point(field_set:metapb.Peer.is_learner)
}

// -------------------------------------------------------------------

// RegionLocalState

// uint64 last_index = 1;
inline void RegionLocalState::clear_last_index() {
  last_index_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 RegionLocalState::last_index() const {
  // @@protoc_insertion_point(field_get:metapb.RegionLocalState.last_index)
  return last_index_;
}
inline void RegionLocalState::set_last_index(::google::protobuf::uint64 value) {
  
  last_index_ = value;
  // @@protoc_insertion_point(field_set:metapb.RegionLocalState.last_index)
}

// uint64 committed_index = 2;
inline void RegionLocalState::clear_committed_index() {
  committed_index_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 RegionLocalState::committed_index() const {
  // @@protoc_insertion_point(field_get:metapb.RegionLocalState.committed_index)
  return committed_index_;
}
inline void RegionLocalState::set_committed_index(::google::protobuf::uint64 value) {
  
  committed_index_ = value;
  // @@protoc_insertion_point(field_set:metapb.RegionLocalState.committed_index)
}

// uint64 applied_index = 3;
inline void RegionLocalState::clear_applied_index() {
  applied_index_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 RegionLocalState::applied_index() const {
  // @@protoc_insertion_point(field_get:metapb.RegionLocalState.applied_index)
  return applied_index_;
}
inline void RegionLocalState::set_applied_index(::google::protobuf::uint64 value) {
  
  applied_index_ = value;
  // @@protoc_insertion_point(field_set:metapb.RegionLocalState.applied_index)
}

// -------------------------------------------------------------------

// Progress

// uint64 matched = 1;
inline void Progress::clear_matched() {
  matched_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Progress::matched() const {
  // @@protoc_insertion_point(field_get:metapb.Progress.matched)
  return matched_;
}
inline void Progress::set_matched(::google::protobuf::uint64 value) {
  
  matched_ = value;
  // @@protoc_insertion_point(field_set:metapb.Progress.matched)
}

// uint64 next_idx = 2;
inline void Progress::clear_next_idx() {
  next_idx_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Progress::next_idx() const {
  // @@protoc_insertion_point(field_get:metapb.Progress.next_idx)
  return next_idx_;
}
inline void Progress::set_next_idx(::google::protobuf::uint64 value) {
  
  next_idx_ = value;
  // @@protoc_insertion_point(field_set:metapb.Progress.next_idx)
}

// bool paused = 3;
inline void Progress::clear_paused() {
  paused_ = false;
}
inline bool Progress::paused() const {
  // @@protoc_insertion_point(field_get:metapb.Progress.paused)
  return paused_;
}
inline void Progress::set_paused(bool value) {
  
  paused_ = value;
  // @@protoc_insertion_point(field_set:metapb.Progress.paused)
}

// uint64 pending_snapshot = 4;
inline void Progress::clear_pending_snapshot() {
  pending_snapshot_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Progress::pending_snapshot() const {
  // @@protoc_insertion_point(field_get:metapb.Progress.pending_snapshot)
  return pending_snapshot_;
}
inline void Progress::set_pending_snapshot(::google::protobuf::uint64 value) {
  
  pending_snapshot_ = value;
  // @@protoc_insertion_point(field_set:metapb.Progress.pending_snapshot)
}

// bool is_learner = 5;
inline void Progress::clear_is_learner() {
  is_learner_ = false;
}
inline bool Progress::is_learner() const {
  // @@protoc_insertion_point(field_get:metapb.Progress.is_learner)
  return is_learner_;
}
inline void Progress::set_is_learner(bool value) {
  
  is_learner_ = value;
  // @@protoc_insertion_point(field_set:metapb.Progress.is_learner)
}

// .metapb.ProgressState state = 6;
inline void Progress::clear_state() {
  state_ = 0;
}
inline ::metapb::ProgressState Progress::state() const {
  // @@protoc_insertion_point(field_get:metapb.Progress.state)
  return static_cast< ::metapb::ProgressState >(state_);
}
inline void Progress::set_state(::metapb::ProgressState value) {
  
  state_ = value;
  // @@protoc_insertion_point(field_set:metapb.Progress.state)
}

// -------------------------------------------------------------------

// PeerStats

// .metapb.Peer peer = 1;
inline bool PeerStats::has_peer() const {
  return this != internal_default_instance() && peer_ != NULL;
}
inline void PeerStats::clear_peer() {
  if (GetArenaNoVirtual() == NULL && peer_ != NULL) {
    delete peer_;
  }
  peer_ = NULL;
}
inline const ::metapb::Peer& PeerStats::_internal_peer() const {
  return *peer_;
}
inline const ::metapb::Peer& PeerStats::peer() const {
  const ::metapb::Peer* p = peer_;
  // @@protoc_insertion_point(field_get:metapb.PeerStats.peer)
  return p != NULL ? *p : *reinterpret_cast<const ::metapb::Peer*>(
      &::metapb::_Peer_default_instance_);
}
inline ::metapb::Peer* PeerStats::release_peer() {
  // @@protoc_insertion_point(field_release:metapb.PeerStats.peer)
  
  ::metapb::Peer* temp = peer_;
  peer_ = NULL;
  return temp;
}
inline ::metapb::Peer* PeerStats::mutable_peer() {
  
  if (peer_ == NULL) {
    auto* p = CreateMaybeMessage<::metapb::Peer>(GetArenaNoVirtual());
    peer_ = p;
  }
  // @@protoc_insertion_point(field_mutable:metapb.PeerStats.peer)
  return peer_;
}
inline void PeerStats::set_allocated_peer(::metapb::Peer* peer) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete peer_;
  }
  if (peer) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      peer = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, peer, submessage_arena);
    }
    
  } else {
    
  }
  peer_ = peer;
  // @@protoc_insertion_point(field_set_allocated:metapb.PeerStats.peer)
}

// uint64 down_seconds = 2;
inline void PeerStats::clear_down_seconds() {
  down_seconds_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 PeerStats::down_seconds() const {
  // @@protoc_insertion_point(field_get:metapb.PeerStats.down_seconds)
  return down_seconds_;
}
inline void PeerStats::set_down_seconds(::google::protobuf::uint64 value) {
  
  down_seconds_ = value;
  // @@protoc_insertion_point(field_set:metapb.PeerStats.down_seconds)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace metapb

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::metapb::StoreState> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::metapb::StoreState>() {
  return ::metapb::StoreState_descriptor();
}
template <> struct is_proto_enum< ::metapb::ProgressState> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::metapb::ProgressState>() {
  return ::metapb::ProgressState_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_metapb_2eproto
