// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tikvpb.proto

#ifndef PROTOBUF_tikvpb_2eproto__INCLUDED
#define PROTOBUF_tikvpb_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include "coprocessor.pb.h"
#include "kvrpcpb.pb.h"
#include "raft_serverpb.pb.h"
#include "gogoproto/gogo.pb.h"
// @@protoc_insertion_point(includes)

namespace tikvpb {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_tikvpb_2eproto();
void protobuf_InitDefaults_tikvpb_2eproto();
void protobuf_AssignDesc_tikvpb_2eproto();
void protobuf_ShutdownFile_tikvpb_2eproto();


// ===================================================================


// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace tikvpb

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_tikvpb_2eproto__INCLUDED
